# wrangler.toml (Workers Sites + Durable Objects)
name = "unique-betting-game"
type = "javascript"
compatibility_date = "2025-06-14"
account_id = "8914dc9a5c0cbfaac15869563ec849ce"

# Durable Object namespace
[[durable_objects.namespaces]]
binding = "GAME_ROOM"
class_name = "GameRoom"

[site]
bucket = "frontend/out"
entry-point = "workers-site"

[build]
command = "npm install --prefix frontend && npm run build --prefix frontend && next export --prefix frontend"
upload = { format = "modules", dir = "frontend/out" }
