# wrangler.toml (Workers Sites + Durable Objects)
name = "unique-betting-game"
type = "javascript"
compatibility_date = "2025-06-14"
account_id = "<YOUR_ACCOUNT_ID>"  # add your Cloudflare account ID

# Durable Object namespace
[[durable_objects.namespaces]]
binding = "GAME_ROOM"
class_name = "GameRoom"

[site]
bucket = "frontend/out"
entry-point = "workers-site"

[build]
command = "npm install --prefix frontend && npm run build --prefix frontend && npm run export --prefix frontend"
upload = { format = "modules", dir = "frontend/out" }
