# wrangler.toml
name = "unique-betting-game"
main = "functions/index.js"
compatibility_date = "2025-06-14"

[[durable_objects.namespaces]]
binding = "GAME_ROOM"
class_name = "GameRoom"

[build]
command = "npm install && npm run build"
upload = { format = "modules" }

# Cloudflare Pages settings
# Build the frontend into a static export
pages_build_output_dir = "frontend/out"

{
  "name": "unique-betting-game-ui",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "react": "^18.0.0",
    "next": "^13.0.0",
    "reconnecting-websocket": "^4.4.0",
    "shadcn-ui": "^1.0.0",
    "framer-motion": "^7.0.0"
  }
}
